spring.application.name=jcash-bank

# PostgreSQL Database (With Docker environment variable fallback)
spring.datasource.url=${SPRING_DATASOURCE_URL:${POSTGRES_URL}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${POSTGRES_USER}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORDD:${POSTGRES_PASSWORD}}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Thymeleaf
spring.thymeleaf.cache=false

# Server
server.port=8080

# Spring Mail SMTP Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_SMTP_USERNAME}
spring.mail.password=${MAIL_SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true